[package]
name = "owe-sceneviewer"
version.workspace = true

[[bin]]
name = "SceneViewer"
sources = ["SceneViewer.cpp", "GlfwCocoaLayer.cpp", "StdinJsonControl.cppm"]

[usage]
options = [
  "-Wextra",
  "-Wno-missing-field-initializers",
  "-Wno-gnu-zero-variadic-macro-arguments",
]
[[when]]
condition = 'target.os == "macos"'

[when.usage]
linker-options = ["-Wl,-sectcreate,__TEXT,__info_plist,Info.plist"]

[dependencies.rstd-log]
workspace = true

[dependencies.owe-core]
workspace = true

[dependencies.owe-viewer-common]
workspace = true

[dependencies.owe-scene]
workspace = true

[dependencies.vvk]
workspace = true
