[package]
name = "owe-viewer-common"
version.workspace = true

[lib]
name = "owe-viewer-common"
module = "viewer.common"
archive = "owe-viewer-common"
sources = [
  "Common.cppm",
  "Audio.cppm",
  "Arg.cppm",
  "Common.cpp",
  "GlfwVulkan.cppm",
]

[usage]
public-include-directories = ["."]
options = [
  "-Wextra",
  "-Wno-missing-field-initializers",
  "-Wno-gnu-zero-variadic-macro-arguments",
]

[dependencies.owe-core]
workspace = true
pub = true

[dependencies.owe-audio]
workspace = true
pub = true

[dependencies.rstd-std]
workspace = true
pub = true

[dependencies.rstd-cppstd]
workspace = true
pub = true

[dependencies.rstd-argparse]
workspace = true
pub = true

[dependencies.wavsen]
workspace = true
pub = true

[dependencies.vvk]
workspace = true
pub = true

[external-dependencies.pkg-config.glfw]
workspace = true
pub = true
