[package]
name = "owe-waywallen-web-renderer"
version.workspace = true

[[bin]]
name = "waywallen-weweb-renderer"
module = "waywallen.web_entry"
sources = [
  "web_entry.cppm",
  "web_entry.cpp",
  "Settings.cppm",
  "WebProducerDevice.cppm",
  "WebProducerDevice.cpp",
  "web_main.cpp",
]

[usage]
options = [
  "-Wextra",
  "-Wno-missing-field-initializers",
  "-Wno-gnu-zero-variadic-macro-arguments",
]
threads = true

[dependencies.owe-audio]
workspace = true

[dependencies.owe-core]
workspace = true

[dependencies.owe-waywallen-producer]
workspace = true

[dependencies.owe-web]
workspace = true

[dependencies.rstd-argparse]
workspace = true

[dependencies.rstd-cppstd]
workspace = true

[dependencies.rstd-log]
workspace = true

[dependencies.rstd-std]
workspace = true

[dependencies.vvk]
workspace = true
