[package]
name = "owe-waywallen-producer"
version.workspace = true

[lib]
name = "owe-waywallen-producer"
module = "waywallen.bridge_producer_core"
archive = "waywallen-bridge-producer"
sources = [
  "Bridge.cppm",
  "BridgeSession.cppm",
  "BridgeSession.cpp",
  "BridgeProducerCore.cppm",
  "BridgeProducerCore.cpp",
  "BridgeAudio.cppm",
]

[usage]
public-include-directories = ["."]
options = [
  "-Wextra",
  "-Wno-missing-field-initializers",
]

[dependencies.owe-audio]
workspace = true
visibility = "public"

[dependencies.rstd-cppstd]
workspace = true
visibility = "public"

[dependencies.rstd-std]
workspace = true
visibility = "public"

[dependencies.rstd-log]
workspace = true
visibility = "private"

[dependencies.vvk]
workspace = true
visibility = "public"

[external-dependencies.pkg-config.waywallen-bridge]
workspace = true
visibility = "public"
