[package]
name = "owe-webviewer"
version.workspace = true

[source-groups.linux]
sources = [
  "EglPresenter.cppm",
  "EglPresenter.cpp",
]

[[bin]]
name = "WebViewer"
module = "viewer.web"
sources = [
  "Web.cppm",
  "Presenter.cppm",
  "VulkanBlitter.cppm",
  "VulkanBlitter.cpp",
  "WebViewer.cpp",
]

when = [
  { condition = 'target.os == "linux"', source-groups = ["linux"] },
]

[usage]
options = [
  "-Wextra",
  "-Wno-missing-field-initializers",
  "-Wno-gnu-zero-variadic-macro-arguments",
]
threads = true

[[when]]
condition = 'target.os == "macos"'

[when.usage]
linker-options = ["-Wl,-sectcreate,__TEXT,__info_plist,Info.plist"]

[dependencies.owe-core]
workspace = true

[dependencies.owe-audio]
workspace = true

[dependencies.owe-viewer-common]
workspace = true

[dependencies.owe-web]
workspace = true

[dependencies.rstd-cppstd]
workspace = true

[dependencies.rstd-argparse]
workspace = true

[dependencies.wavsen]
workspace = true

[dependencies.vvk]
workspace = true

[external-dependencies.pkg-config.glfw]
workspace = true

[external-dependencies.pkg-config.egl]
workspace = true
condition = 'target.os == "linux"'

[external-dependencies.pkg-config.gles]
workspace = true
condition = 'target.os == "linux"'

[external-dependencies.pkg-config.x11]
workspace = true
condition = 'target.os == "linux"'

[external-dependencies.pkg-config.wayland-egl]
workspace = true
condition = 'target.os == "linux"'
